version: "3.8"
services:
  client:
    build: ./front_end
    ports:
      - 8081:8081
  server:
    build: ./back_end
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "mongodb://db:27017/book-store" 
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - MERN_project:/data/db 
volumes:
  MERN_project:


